version: "3.9"

services:
  recommender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recommender-catboost
    volumes:
      - .:/app
    working_dir: /app
    command: poetry run python src/run_pipeline.py
